### ISSUE TITLE
Auto-calculate utilisation percentage based on hours inputted

### ISSUE THREAD

**Issue by mikef80** [GlennHS/Scrum-Helper#24]
**Is your feature request related to a problem? Please describe.**
No - not a problem!

**Describe the solution you'd like**
I'd like the total expected hours for all tasks that are not blocked to be worked against a standard working day to autocalculate expected utilisation. This can the auto-populate the utilisation field, whilst still allowing the ability to overwrite if needed.

**Comment by GlennHS** [comment]
Relates to #15 but won't be fixed by it. Valid issue, will be added to next minor release, ETA 27/10
